# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: deployement

on:
  push:
    branches: [CICD]
  pull_request:
    branches: [CICD]

jobs:
  deployement:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_LOGIN }}
          known_hosts: ${{ secrets.SSH_KNOWHOSTS }}
      - name: rsync over ssh
        run: rsync ./foo/ user@remote:bar/
        script: whoami && ls -la
      - name: check git
        uses: actions/checkout@v2
        with:
          repository: Kraystone/MSPR-Script
          ref: master
      - name: java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: compilation
        working-directory: ./src/main/java
        run:
          mvn clean install compile package
      - name: list files
        run:
          ls -la
      
      - run: echo "Job done !"